
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema patient_data_batch_loader
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `BATCH_JOB_INSTANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_JOB_INSTANCE` ;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_INSTANCE` (
    `JOB_INSTANCE_ID` INT NOT NULL AUTO_INCREMENT,
    `VERSION` INT,
    `JOB_NAME` VARCHAR(100) NOT NULL,
    `JOB_KEY` VARCHAR(32) NOT NULL,
    `slug` VARCHAR(32) NOT NULL,
    `description` TEXT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`JOB_INSTANCE_ID`),
    UNIQUE INDEX `JOB_INST_UN` (`JOB_NAME`, `JOB_KEY`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BATCH_JOB_EXECUTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_JOB_EXECUTION` ;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION` (
    `JOB_EXECUTION_ID` INT NOT NULL AUTO_INCREMENT,
    `VERSION` INT,
    `JOB_INSTANCE_ID` INT NOT NULL,
    `CREATE_TIME` TIMESTAMP NOT NULL,
    `START_TIME` TIMESTAMP NULL,
    `END_TIME` TIMESTAMP NULL,
    `STATUS` VARCHAR(10),
    `EXIT_CODE` VARCHAR(2500),
    `EXIT_MESSAGE` VARCHAR(2500),
    `LAST_UPDATED` TIMESTAMP,
    `JOB_CONFIGURATION_LOCATION` VARCHAR(2500),
    PRIMARY KEY (`JOB_EXECUTION_ID`),
    CONSTRAINT `JOB_INST_EXEC_FK`
    FOREIGN KEY (`JOB_INSTANCE_ID`)
    REFERENCES `BATCH_JOB_INSTANCE` (`JOB_INSTANCE_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BATCH_JOB_EXECUTION_PARAMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_JOB_EXECUTION_PARAMS` ;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_PARAMS` (
     `JOB_EXECUTION_ID` INT NOT NULL AUTO_INCREMENT,
     `LONG_VAL` INT,
     `DOUBLE_VAL` DOUBLE ,
     `DATE_VAL` TIMESTAMP NULL,
     `TYPE_CD` VARCHAR(6) NOT NULL,
     `KEY_NAME` VARCHAR(100),
    `STRING_VAL` VARCHAR(250),
    `IDENTIFYING` CHAR(1) NOT NULL,
    PRIMARY KEY (`JOB_EXECUTION_ID`),
    CONSTRAINT `JOB_EXEC_PARAMS_FK`
    FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BATCH_STEP_EXECUTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_STEP_EXECUTION` ;

CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION` (
    `STEP_EXECUTION_ID` INT NOT NULL AUTO_INCREMENT,
    `JOB_EXECUTION_ID` INT NOT NULL,
    `VERSION` INT NOT NULL,
    `START_TIME` TIMESTAMP NOT NULL,
    `END_TIME` TIMESTAMP NULL,
    `LAST_UPDATED` TIMESTAMP,
    `STEP_NAME` VARCHAR(100) NOT NULL,
    `STATUS` VARCHAR(10),
    `COMMIT_COUNT` INT,
    `READ_COUNT` INT,
    `FILTER_COUNT` INT,
    `WRITE_COUNT` INT,
    `READ_SKIP_COUNT` INT,
    `WRITE_SKIP_COUNT` INT,
    `PROCESS_SKIP_COUNT` INT,
    `ROLLBACK_COUNT` INT,
    `EXIT_CODE` VARCHAR(2500),
    `EXIT_MESSAGE` VARCHAR(2500),
    PRIMARY KEY (`STEP_EXECUTION_ID`),
    CONSTRAINT `JOB_EXEC_STEP_FK`
    FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BATCH_STEP_EXECUTION_CONTEXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_STEP_EXECUTION_CONTEXT` ;

CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION_CONTEXT` (
    `STEP_EXECUTION_ID` INT NOT NULL AUTO_INCREMENT,
    `SHORT_CONTEXT` VARCHAR(2500) NOT NULL,
    `SERIALIZED_CONTEXT` BLOB,
    PRIMARY KEY (`STEP_EXECUTION_ID`),
    CONSTRAINT `STEP_EXEC_CTX_FK`
    FOREIGN KEY (`STEP_EXECUTION_ID`)
    REFERENCES `BATCH_STEP_EXECUTION` (`STEP_EXECUTION_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `BATCH_JOB_EXECUTION_CONTEXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATCH_JOB_EXECUTION_CONTEXT` ;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_CONTEXT` (
      `JOB_EXECUTION_ID` INT NOT NULL AUTO_INCREMENT,
      `SHORT_CONTEXT` VARCHAR(2500) NOT NULL,
    `SERIALIZED_CONTEXT` BLOB,
    PRIMARY KEY (`JOB_EXECUTION_ID`),
    CONSTRAINT `JOB_EXEC_CTX_FK`
    FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    )
    ENGINE = InnoDB;










